/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitiesIndexRouteImport } from './routes/cities.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PortalQuoteNumberRouteImport } from './routes/portal.$quoteNumber'
import { Route as CitiesCityRouteImport } from './routes/cities.$city'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCompanyIndexRouteImport } from './routes/_authenticated/company.index'
import { Route as ApiPublicSlaTickRouteImport } from './routes/api/public/sla-tick'
import { Route as AuthenticatedCompanySettingsRouteImport } from './routes/_authenticated/company.settings'
import { Route as AuthenticatedCompanyScheduleRouteImport } from './routes/_authenticated/company.schedule'
import { Route as AuthenticatedCompanyProfileRouteImport } from './routes/_authenticated/company.profile'
import { Route as AuthenticatedCompanyNotificationsRouteImport } from './routes/_authenticated/company.notifications'
import { Route as AuthenticatedCompanyMessagesRouteImport } from './routes/_authenticated/company.messages'
import { Route as AuthenticatedCompanyMarketplaceRouteImport } from './routes/_authenticated/company.marketplace'
import { Route as AuthenticatedCompanyLeadsRouteImport } from './routes/_authenticated/company.leads'
import { Route as AuthenticatedCompanyInvoicesRouteImport } from './routes/_authenticated/company.invoices'
import { Route as AuthenticatedCompanyExclusiveRouteImport } from './routes/_authenticated/company.exclusive'
import { Route as AuthenticatedCompanyEstimatesRouteImport } from './routes/_authenticated/company.estimates'
import { Route as AuthenticatedCompanyDocumentsRouteImport } from './routes/_authenticated/company.documents'
import { Route as AuthenticatedCompanyDashboardRouteImport } from './routes/_authenticated/company.dashboard'
import { Route as AuthenticatedCompanyCustomersRouteImport } from './routes/_authenticated/company.customers'
import { Route as AuthenticatedCompanyAnalyticsRouteImport } from './routes/_authenticated/company.analytics'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin.companies'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalQuoteNumberRoute = PortalQuoteNumberRouteImport.update({
  id: '/portal/$quoteNumber',
  path: '/portal/$quoteNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCityRoute = CitiesCityRouteImport.update({
  id: '/cities/$city',
  path: '/cities/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyIndexRoute =
  AuthenticatedCompanyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const ApiPublicSlaTickRoute = ApiPublicSlaTickRouteImport.update({
  id: '/api/public/sla-tick',
  path: '/api/public/sla-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompanySettingsRoute =
  AuthenticatedCompanySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyScheduleRoute =
  AuthenticatedCompanyScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyProfileRoute =
  AuthenticatedCompanyProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyNotificationsRoute =
  AuthenticatedCompanyNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyMessagesRoute =
  AuthenticatedCompanyMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyMarketplaceRoute =
  AuthenticatedCompanyMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyLeadsRoute =
  AuthenticatedCompanyLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyInvoicesRoute =
  AuthenticatedCompanyInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyExclusiveRoute =
  AuthenticatedCompanyExclusiveRouteImport.update({
    id: '/exclusive',
    path: '/exclusive',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyEstimatesRoute =
  AuthenticatedCompanyEstimatesRouteImport.update({
    id: '/estimates',
    path: '/estimates',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyDocumentsRoute =
  AuthenticatedCompanyDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyDashboardRoute =
  AuthenticatedCompanyDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyCustomersRoute =
  AuthenticatedCompanyCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyAnalyticsRoute =
  AuthenticatedCompanyAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/company': typeof AuthenticatedCompanyRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cities/$city': typeof CitiesCityRoute
  '/portal/$quoteNumber': typeof PortalQuoteNumberRoute
  '/blog/': typeof BlogIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/company/analytics': typeof AuthenticatedCompanyAnalyticsRoute
  '/company/customers': typeof AuthenticatedCompanyCustomersRoute
  '/company/dashboard': typeof AuthenticatedCompanyDashboardRoute
  '/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/company/estimates': typeof AuthenticatedCompanyEstimatesRoute
  '/company/exclusive': typeof AuthenticatedCompanyExclusiveRoute
  '/company/invoices': typeof AuthenticatedCompanyInvoicesRoute
  '/company/leads': typeof AuthenticatedCompanyLeadsRoute
  '/company/marketplace': typeof AuthenticatedCompanyMarketplaceRoute
  '/company/messages': typeof AuthenticatedCompanyMessagesRoute
  '/company/notifications': typeof AuthenticatedCompanyNotificationsRoute
  '/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/company/schedule': typeof AuthenticatedCompanyScheduleRoute
  '/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/api/public/sla-tick': typeof ApiPublicSlaTickRoute
  '/company/': typeof AuthenticatedCompanyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cities/$city': typeof CitiesCityRoute
  '/portal/$quoteNumber': typeof PortalQuoteNumberRoute
  '/blog': typeof BlogIndexRoute
  '/cities': typeof CitiesIndexRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/company/analytics': typeof AuthenticatedCompanyAnalyticsRoute
  '/company/customers': typeof AuthenticatedCompanyCustomersRoute
  '/company/dashboard': typeof AuthenticatedCompanyDashboardRoute
  '/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/company/estimates': typeof AuthenticatedCompanyEstimatesRoute
  '/company/exclusive': typeof AuthenticatedCompanyExclusiveRoute
  '/company/invoices': typeof AuthenticatedCompanyInvoicesRoute
  '/company/leads': typeof AuthenticatedCompanyLeadsRoute
  '/company/marketplace': typeof AuthenticatedCompanyMarketplaceRoute
  '/company/messages': typeof AuthenticatedCompanyMessagesRoute
  '/company/notifications': typeof AuthenticatedCompanyNotificationsRoute
  '/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/company/schedule': typeof AuthenticatedCompanyScheduleRoute
  '/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/api/public/sla-tick': typeof ApiPublicSlaTickRoute
  '/company': typeof AuthenticatedCompanyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/company': typeof AuthenticatedCompanyRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cities/$city': typeof CitiesCityRoute
  '/portal/$quoteNumber': typeof PortalQuoteNumberRoute
  '/blog/': typeof BlogIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/company/analytics': typeof AuthenticatedCompanyAnalyticsRoute
  '/_authenticated/company/customers': typeof AuthenticatedCompanyCustomersRoute
  '/_authenticated/company/dashboard': typeof AuthenticatedCompanyDashboardRoute
  '/_authenticated/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/_authenticated/company/estimates': typeof AuthenticatedCompanyEstimatesRoute
  '/_authenticated/company/exclusive': typeof AuthenticatedCompanyExclusiveRoute
  '/_authenticated/company/invoices': typeof AuthenticatedCompanyInvoicesRoute
  '/_authenticated/company/leads': typeof AuthenticatedCompanyLeadsRoute
  '/_authenticated/company/marketplace': typeof AuthenticatedCompanyMarketplaceRoute
  '/_authenticated/company/messages': typeof AuthenticatedCompanyMessagesRoute
  '/_authenticated/company/notifications': typeof AuthenticatedCompanyNotificationsRoute
  '/_authenticated/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/_authenticated/company/schedule': typeof AuthenticatedCompanyScheduleRoute
  '/_authenticated/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/api/public/sla-tick': typeof ApiPublicSlaTickRoute
  '/_authenticated/company/': typeof AuthenticatedCompanyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/admin'
    | '/company'
    | '/dashboard'
    | '/blog/$slug'
    | '/cities/$city'
    | '/portal/$quoteNumber'
    | '/blog/'
    | '/cities/'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/company/analytics'
    | '/company/customers'
    | '/company/dashboard'
    | '/company/documents'
    | '/company/estimates'
    | '/company/exclusive'
    | '/company/invoices'
    | '/company/leads'
    | '/company/marketplace'
    | '/company/messages'
    | '/company/notifications'
    | '/company/profile'
    | '/company/schedule'
    | '/company/settings'
    | '/api/public/sla-tick'
    | '/company/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/admin'
    | '/dashboard'
    | '/blog/$slug'
    | '/cities/$city'
    | '/portal/$quoteNumber'
    | '/blog'
    | '/cities'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/company/analytics'
    | '/company/customers'
    | '/company/dashboard'
    | '/company/documents'
    | '/company/estimates'
    | '/company/exclusive'
    | '/company/invoices'
    | '/company/leads'
    | '/company/marketplace'
    | '/company/messages'
    | '/company/notifications'
    | '/company/profile'
    | '/company/schedule'
    | '/company/settings'
    | '/api/public/sla-tick'
    | '/company'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/_authenticated/admin'
    | '/_authenticated/company'
    | '/_authenticated/dashboard'
    | '/blog/$slug'
    | '/cities/$city'
    | '/portal/$quoteNumber'
    | '/blog/'
    | '/cities/'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/company/analytics'
    | '/_authenticated/company/customers'
    | '/_authenticated/company/dashboard'
    | '/_authenticated/company/documents'
    | '/_authenticated/company/estimates'
    | '/_authenticated/company/exclusive'
    | '/_authenticated/company/invoices'
    | '/_authenticated/company/leads'
    | '/_authenticated/company/marketplace'
    | '/_authenticated/company/messages'
    | '/_authenticated/company/notifications'
    | '/_authenticated/company/profile'
    | '/_authenticated/company/schedule'
    | '/_authenticated/company/settings'
    | '/api/public/sla-tick'
    | '/_authenticated/company/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CitiesCityRoute: typeof CitiesCityRoute
  PortalQuoteNumberRoute: typeof PortalQuoteNumberRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
  ApiPublicSlaTickRoute: typeof ApiPublicSlaTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/': {
      id: '/cities/'
      path: '/cities'
      fullPath: '/cities/'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$quoteNumber': {
      id: '/portal/$quoteNumber'
      path: '/portal/$quoteNumber'
      fullPath: '/portal/$quoteNumber'
      preLoaderRoute: typeof PortalQuoteNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$city': {
      id: '/cities/$city'
      path: '/cities/$city'
      fullPath: '/cities/$city'
      preLoaderRoute: typeof CitiesCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company/': {
      id: '/_authenticated/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof AuthenticatedCompanyIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/api/public/sla-tick': {
      id: '/api/public/sla-tick'
      path: '/api/public/sla-tick'
      fullPath: '/api/public/sla-tick'
      preLoaderRoute: typeof ApiPublicSlaTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/company/settings': {
      id: '/_authenticated/company/settings'
      path: '/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof AuthenticatedCompanySettingsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/schedule': {
      id: '/_authenticated/company/schedule'
      path: '/schedule'
      fullPath: '/company/schedule'
      preLoaderRoute: typeof AuthenticatedCompanyScheduleRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/profile': {
      id: '/_authenticated/company/profile'
      path: '/profile'
      fullPath: '/company/profile'
      preLoaderRoute: typeof AuthenticatedCompanyProfileRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/notifications': {
      id: '/_authenticated/company/notifications'
      path: '/notifications'
      fullPath: '/company/notifications'
      preLoaderRoute: typeof AuthenticatedCompanyNotificationsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/messages': {
      id: '/_authenticated/company/messages'
      path: '/messages'
      fullPath: '/company/messages'
      preLoaderRoute: typeof AuthenticatedCompanyMessagesRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/marketplace': {
      id: '/_authenticated/company/marketplace'
      path: '/marketplace'
      fullPath: '/company/marketplace'
      preLoaderRoute: typeof AuthenticatedCompanyMarketplaceRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/leads': {
      id: '/_authenticated/company/leads'
      path: '/leads'
      fullPath: '/company/leads'
      preLoaderRoute: typeof AuthenticatedCompanyLeadsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/invoices': {
      id: '/_authenticated/company/invoices'
      path: '/invoices'
      fullPath: '/company/invoices'
      preLoaderRoute: typeof AuthenticatedCompanyInvoicesRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/exclusive': {
      id: '/_authenticated/company/exclusive'
      path: '/exclusive'
      fullPath: '/company/exclusive'
      preLoaderRoute: typeof AuthenticatedCompanyExclusiveRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/estimates': {
      id: '/_authenticated/company/estimates'
      path: '/estimates'
      fullPath: '/company/estimates'
      preLoaderRoute: typeof AuthenticatedCompanyEstimatesRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/documents': {
      id: '/_authenticated/company/documents'
      path: '/documents'
      fullPath: '/company/documents'
      preLoaderRoute: typeof AuthenticatedCompanyDocumentsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/dashboard': {
      id: '/_authenticated/company/dashboard'
      path: '/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof AuthenticatedCompanyDashboardRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/customers': {
      id: '/_authenticated/company/customers'
      path: '/customers'
      fullPath: '/company/customers'
      preLoaderRoute: typeof AuthenticatedCompanyCustomersRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/analytics': {
      id: '/_authenticated/company/analytics'
      path: '/analytics'
      fullPath: '/company/analytics'
      preLoaderRoute: typeof AuthenticatedCompanyAnalyticsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCompanyRouteChildren {
  AuthenticatedCompanyAnalyticsRoute: typeof AuthenticatedCompanyAnalyticsRoute
  AuthenticatedCompanyCustomersRoute: typeof AuthenticatedCompanyCustomersRoute
  AuthenticatedCompanyDashboardRoute: typeof AuthenticatedCompanyDashboardRoute
  AuthenticatedCompanyDocumentsRoute: typeof AuthenticatedCompanyDocumentsRoute
  AuthenticatedCompanyEstimatesRoute: typeof AuthenticatedCompanyEstimatesRoute
  AuthenticatedCompanyExclusiveRoute: typeof AuthenticatedCompanyExclusiveRoute
  AuthenticatedCompanyInvoicesRoute: typeof AuthenticatedCompanyInvoicesRoute
  AuthenticatedCompanyLeadsRoute: typeof AuthenticatedCompanyLeadsRoute
  AuthenticatedCompanyMarketplaceRoute: typeof AuthenticatedCompanyMarketplaceRoute
  AuthenticatedCompanyMessagesRoute: typeof AuthenticatedCompanyMessagesRoute
  AuthenticatedCompanyNotificationsRoute: typeof AuthenticatedCompanyNotificationsRoute
  AuthenticatedCompanyProfileRoute: typeof AuthenticatedCompanyProfileRoute
  AuthenticatedCompanyScheduleRoute: typeof AuthenticatedCompanyScheduleRoute
  AuthenticatedCompanySettingsRoute: typeof AuthenticatedCompanySettingsRoute
  AuthenticatedCompanyIndexRoute: typeof AuthenticatedCompanyIndexRoute
}

const AuthenticatedCompanyRouteChildren: AuthenticatedCompanyRouteChildren = {
  AuthenticatedCompanyAnalyticsRoute: AuthenticatedCompanyAnalyticsRoute,
  AuthenticatedCompanyCustomersRoute: AuthenticatedCompanyCustomersRoute,
  AuthenticatedCompanyDashboardRoute: AuthenticatedCompanyDashboardRoute,
  AuthenticatedCompanyDocumentsRoute: AuthenticatedCompanyDocumentsRoute,
  AuthenticatedCompanyEstimatesRoute: AuthenticatedCompanyEstimatesRoute,
  AuthenticatedCompanyExclusiveRoute: AuthenticatedCompanyExclusiveRoute,
  AuthenticatedCompanyInvoicesRoute: AuthenticatedCompanyInvoicesRoute,
  AuthenticatedCompanyLeadsRoute: AuthenticatedCompanyLeadsRoute,
  AuthenticatedCompanyMarketplaceRoute: AuthenticatedCompanyMarketplaceRoute,
  AuthenticatedCompanyMessagesRoute: AuthenticatedCompanyMessagesRoute,
  AuthenticatedCompanyNotificationsRoute:
    AuthenticatedCompanyNotificationsRoute,
  AuthenticatedCompanyProfileRoute: AuthenticatedCompanyProfileRoute,
  AuthenticatedCompanyScheduleRoute: AuthenticatedCompanyScheduleRoute,
  AuthenticatedCompanySettingsRoute: AuthenticatedCompanySettingsRoute,
  AuthenticatedCompanyIndexRoute: AuthenticatedCompanyIndexRoute,
}

const AuthenticatedCompanyRouteWithChildren =
  AuthenticatedCompanyRoute._addFileChildren(AuthenticatedCompanyRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  BlogSlugRoute: BlogSlugRoute,
  CitiesCityRoute: CitiesCityRoute,
  PortalQuoteNumberRoute: PortalQuoteNumberRoute,
  BlogIndexRoute: BlogIndexRoute,
  CitiesIndexRoute: CitiesIndexRoute,
  ApiPublicSlaTickRoute: ApiPublicSlaTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
