/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OpenMarketplaceRouteImport } from './routes/open-marketplace'
import { Route as MovingScheduleSoftwareRouteImport } from './routes/moving-schedule-software'
import { Route as MovingLeadsRouteImport } from './routes/moving-leads'
import { Route as MovingEstimateSoftwareRouteImport } from './routes/moving-estimate-software'
import { Route as MovingDispatchSoftwareRouteImport } from './routes/moving-dispatch-software'
import { Route as MovingCompanySoftwareRouteImport } from './routes/moving-company-software'
import { Route as MovingCompanyCrmRouteImport } from './routes/moving-company-crm'
import { Route as LeadGenerationRouteImport } from './routes/lead-generation'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ExclusiveMovingLeadsRouteImport } from './routes/exclusive-moving-leads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnersIndexRouteImport } from './routes/partners.index'
import { Route as CitiesIndexRouteImport } from './routes/cities.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PortalQuoteNumberRouteImport } from './routes/portal.$quoteNumber'
import { Route as PartnersLocationRouteImport } from './routes/partners.$location'
import { Route as LearnTopicRouteImport } from './routes/learn.$topic'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as CitiesCityRouteImport } from './routes/cities.$city'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomerRouteImport } from './routes/_authenticated/customer'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedCompanyIndexRouteImport } from './routes/_authenticated/company.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicSlaTickRouteImport } from './routes/api/public/sla-tick'
import { Route as AuthenticatedCompanySettingsRouteImport } from './routes/_authenticated/company.settings'
import { Route as AuthenticatedCompanyScheduleRouteImport } from './routes/_authenticated/company.schedule'
import { Route as AuthenticatedCompanyProfileRouteImport } from './routes/_authenticated/company.profile'
import { Route as AuthenticatedCompanyNotificationsRouteImport } from './routes/_authenticated/company.notifications'
import { Route as AuthenticatedCompanyMessagesRouteImport } from './routes/_authenticated/company.messages'
import { Route as AuthenticatedCompanyMarketplaceRouteImport } from './routes/_authenticated/company.marketplace'
import { Route as AuthenticatedCompanyLeadsRouteImport } from './routes/_authenticated/company.leads'
import { Route as AuthenticatedCompanyInvoicesRouteImport } from './routes/_authenticated/company.invoices'
import { Route as AuthenticatedCompanyExclusiveRouteImport } from './routes/_authenticated/company.exclusive'
import { Route as AuthenticatedCompanyEstimatesRouteImport } from './routes/_authenticated/company.estimates'
import { Route as AuthenticatedCompanyDocumentsRouteImport } from './routes/_authenticated/company.documents'
import { Route as AuthenticatedCompanyDashboardRouteImport } from './routes/_authenticated/company.dashboard'
import { Route as AuthenticatedCompanyCustomersRouteImport } from './routes/_authenticated/company.customers'
import { Route as AuthenticatedCompanyAnalyticsRouteImport } from './routes/_authenticated/company.analytics'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin.companies'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenMarketplaceRoute = OpenMarketplaceRouteImport.update({
  id: '/open-marketplace',
  path: '/open-marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingScheduleSoftwareRoute = MovingScheduleSoftwareRouteImport.update({
  id: '/moving-schedule-software',
  path: '/moving-schedule-software',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingLeadsRoute = MovingLeadsRouteImport.update({
  id: '/moving-leads',
  path: '/moving-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingEstimateSoftwareRoute = MovingEstimateSoftwareRouteImport.update({
  id: '/moving-estimate-software',
  path: '/moving-estimate-software',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingDispatchSoftwareRoute = MovingDispatchSoftwareRouteImport.update({
  id: '/moving-dispatch-software',
  path: '/moving-dispatch-software',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingCompanySoftwareRoute = MovingCompanySoftwareRouteImport.update({
  id: '/moving-company-software',
  path: '/moving-company-software',
  getParentRoute: () => rootRouteImport,
} as any)
const MovingCompanyCrmRoute = MovingCompanyCrmRouteImport.update({
  id: '/moving-company-crm',
  path: '/moving-company-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadGenerationRoute = LeadGenerationRouteImport.update({
  id: '/lead-generation',
  path: '/lead-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusiveMovingLeadsRoute = ExclusiveMovingLeadsRouteImport.update({
  id: '/exclusive-moving-leads',
  path: '/exclusive-moving-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalQuoteNumberRoute = PortalQuoteNumberRouteImport.update({
  id: '/portal/$quoteNumber',
  path: '/portal/$quoteNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersLocationRoute = PartnersLocationRouteImport.update({
  id: '/partners/$location',
  path: '/partners/$location',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTopicRoute = LearnTopicRouteImport.update({
  id: '/learn/$topic',
  path: '/learn/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCityRoute = CitiesCityRouteImport.update({
  id: '/cities/$city',
  path: '/cities/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerRoute = AuthenticatedCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyIndexRoute =
  AuthenticatedCompanyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSlaTickRoute = ApiPublicSlaTickRouteImport.update({
  id: '/api/public/sla-tick',
  path: '/api/public/sla-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompanySettingsRoute =
  AuthenticatedCompanySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyScheduleRoute =
  AuthenticatedCompanyScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyProfileRoute =
  AuthenticatedCompanyProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyNotificationsRoute =
  AuthenticatedCompanyNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyMessagesRoute =
  AuthenticatedCompanyMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyMarketplaceRoute =
  AuthenticatedCompanyMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyLeadsRoute =
  AuthenticatedCompanyLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyInvoicesRoute =
  AuthenticatedCompanyInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyExclusiveRoute =
  AuthenticatedCompanyExclusiveRouteImport.update({
    id: '/exclusive',
    path: '/exclusive',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyEstimatesRoute =
  AuthenticatedCompanyEstimatesRouteImport.update({
    id: '/estimates',
    path: '/estimates',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyDocumentsRoute =
  AuthenticatedCompanyDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyDashboardRoute =
  AuthenticatedCompanyDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyCustomersRoute =
  AuthenticatedCompanyCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyAnalyticsRoute =
  AuthenticatedCompanyAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/admin/companies',
    path: '/admin/companies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/exclusive-moving-leads': typeof ExclusiveMovingLeadsRoute
  '/join': typeof JoinRoute
  '/lead-generation': typeof LeadGenerationRoute
  '/moving-company-crm': typeof MovingCompanyCrmRoute
  '/moving-company-software': typeof MovingCompanySoftwareRoute
  '/moving-dispatch-software': typeof MovingDispatchSoftwareRoute
  '/moving-estimate-software': typeof MovingEstimateSoftwareRoute
  '/moving-leads': typeof MovingLeadsRoute
  '/moving-schedule-software': typeof MovingScheduleSoftwareRoute
  '/open-marketplace': typeof OpenMarketplaceRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/company': typeof AuthenticatedCompanyRouteWithChildren
  '/customer': typeof AuthenticatedCustomerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cities/$city': typeof CitiesCityRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/partners/$location': typeof PartnersLocationRoute
  '/portal/$quoteNumber': typeof PortalQuoteNumberRoute
  '/blog/': typeof BlogIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/company/analytics': typeof AuthenticatedCompanyAnalyticsRoute
  '/company/customers': typeof AuthenticatedCompanyCustomersRoute
  '/company/dashboard': typeof AuthenticatedCompanyDashboardRoute
  '/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/company/estimates': typeof AuthenticatedCompanyEstimatesRoute
  '/company/exclusive': typeof AuthenticatedCompanyExclusiveRoute
  '/company/invoices': typeof AuthenticatedCompanyInvoicesRoute
  '/company/leads': typeof AuthenticatedCompanyLeadsRoute
  '/company/marketplace': typeof AuthenticatedCompanyMarketplaceRoute
  '/company/messages': typeof AuthenticatedCompanyMessagesRoute
  '/company/notifications': typeof AuthenticatedCompanyNotificationsRoute
  '/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/company/schedule': typeof AuthenticatedCompanyScheduleRoute
  '/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/api/public/sla-tick': typeof ApiPublicSlaTickRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/company/': typeof AuthenticatedCompanyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/exclusive-moving-leads': typeof ExclusiveMovingLeadsRoute
  '/join': typeof JoinRoute
  '/lead-generation': typeof LeadGenerationRoute
  '/moving-company-crm': typeof MovingCompanyCrmRoute
  '/moving-company-software': typeof MovingCompanySoftwareRoute
  '/moving-dispatch-software': typeof MovingDispatchSoftwareRoute
  '/moving-estimate-software': typeof MovingEstimateSoftwareRoute
  '/moving-leads': typeof MovingLeadsRoute
  '/moving-schedule-software': typeof MovingScheduleSoftwareRoute
  '/open-marketplace': typeof OpenMarketplaceRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/customer': typeof AuthenticatedCustomerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cities/$city': typeof CitiesCityRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/partners/$location': typeof PartnersLocationRoute
  '/portal/$quoteNumber': typeof PortalQuoteNumberRoute
  '/blog': typeof BlogIndexRoute
  '/cities': typeof CitiesIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/company/analytics': typeof AuthenticatedCompanyAnalyticsRoute
  '/company/customers': typeof AuthenticatedCompanyCustomersRoute
  '/company/dashboard': typeof AuthenticatedCompanyDashboardRoute
  '/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/company/estimates': typeof AuthenticatedCompanyEstimatesRoute
  '/company/exclusive': typeof AuthenticatedCompanyExclusiveRoute
  '/company/invoices': typeof AuthenticatedCompanyInvoicesRoute
  '/company/leads': typeof AuthenticatedCompanyLeadsRoute
  '/company/marketplace': typeof AuthenticatedCompanyMarketplaceRoute
  '/company/messages': typeof AuthenticatedCompanyMessagesRoute
  '/company/notifications': typeof AuthenticatedCompanyNotificationsRoute
  '/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/company/schedule': typeof AuthenticatedCompanyScheduleRoute
  '/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/api/public/sla-tick': typeof ApiPublicSlaTickRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/company': typeof AuthenticatedCompanyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/exclusive-moving-leads': typeof ExclusiveMovingLeadsRoute
  '/join': typeof JoinRoute
  '/lead-generation': typeof LeadGenerationRoute
  '/moving-company-crm': typeof MovingCompanyCrmRoute
  '/moving-company-software': typeof MovingCompanySoftwareRoute
  '/moving-dispatch-software': typeof MovingDispatchSoftwareRoute
  '/moving-estimate-software': typeof MovingEstimateSoftwareRoute
  '/moving-leads': typeof MovingLeadsRoute
  '/moving-schedule-software': typeof MovingScheduleSoftwareRoute
  '/open-marketplace': typeof OpenMarketplaceRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/_authenticated/company': typeof AuthenticatedCompanyRouteWithChildren
  '/_authenticated/customer': typeof AuthenticatedCustomerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cities/$city': typeof CitiesCityRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/partners/$location': typeof PartnersLocationRoute
  '/portal/$quoteNumber': typeof PortalQuoteNumberRoute
  '/blog/': typeof BlogIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/company/analytics': typeof AuthenticatedCompanyAnalyticsRoute
  '/_authenticated/company/customers': typeof AuthenticatedCompanyCustomersRoute
  '/_authenticated/company/dashboard': typeof AuthenticatedCompanyDashboardRoute
  '/_authenticated/company/documents': typeof AuthenticatedCompanyDocumentsRoute
  '/_authenticated/company/estimates': typeof AuthenticatedCompanyEstimatesRoute
  '/_authenticated/company/exclusive': typeof AuthenticatedCompanyExclusiveRoute
  '/_authenticated/company/invoices': typeof AuthenticatedCompanyInvoicesRoute
  '/_authenticated/company/leads': typeof AuthenticatedCompanyLeadsRoute
  '/_authenticated/company/marketplace': typeof AuthenticatedCompanyMarketplaceRoute
  '/_authenticated/company/messages': typeof AuthenticatedCompanyMessagesRoute
  '/_authenticated/company/notifications': typeof AuthenticatedCompanyNotificationsRoute
  '/_authenticated/company/profile': typeof AuthenticatedCompanyProfileRoute
  '/_authenticated/company/schedule': typeof AuthenticatedCompanyScheduleRoute
  '/_authenticated/company/settings': typeof AuthenticatedCompanySettingsRoute
  '/api/public/sla-tick': typeof ApiPublicSlaTickRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/company/': typeof AuthenticatedCompanyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/exclusive-moving-leads'
    | '/join'
    | '/lead-generation'
    | '/moving-company-crm'
    | '/moving-company-software'
    | '/moving-dispatch-software'
    | '/moving-estimate-software'
    | '/moving-leads'
    | '/moving-schedule-software'
    | '/open-marketplace'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/company'
    | '/customer'
    | '/dashboard'
    | '/blog/$slug'
    | '/cities/$city'
    | '/compare/$slug'
    | '/learn/$topic'
    | '/partners/$location'
    | '/portal/$quoteNumber'
    | '/blog/'
    | '/cities/'
    | '/partners/'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/company/analytics'
    | '/company/customers'
    | '/company/dashboard'
    | '/company/documents'
    | '/company/estimates'
    | '/company/exclusive'
    | '/company/invoices'
    | '/company/leads'
    | '/company/marketplace'
    | '/company/messages'
    | '/company/notifications'
    | '/company/profile'
    | '/company/schedule'
    | '/company/settings'
    | '/api/public/sla-tick'
    | '/admin/'
    | '/company/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/exclusive-moving-leads'
    | '/join'
    | '/lead-generation'
    | '/moving-company-crm'
    | '/moving-company-software'
    | '/moving-dispatch-software'
    | '/moving-estimate-software'
    | '/moving-leads'
    | '/moving-schedule-software'
    | '/open-marketplace'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/customer'
    | '/dashboard'
    | '/blog/$slug'
    | '/cities/$city'
    | '/compare/$slug'
    | '/learn/$topic'
    | '/partners/$location'
    | '/portal/$quoteNumber'
    | '/blog'
    | '/cities'
    | '/partners'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/company/analytics'
    | '/company/customers'
    | '/company/dashboard'
    | '/company/documents'
    | '/company/estimates'
    | '/company/exclusive'
    | '/company/invoices'
    | '/company/leads'
    | '/company/marketplace'
    | '/company/messages'
    | '/company/notifications'
    | '/company/profile'
    | '/company/schedule'
    | '/company/settings'
    | '/api/public/sla-tick'
    | '/admin'
    | '/company'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/calculator'
    | '/contact'
    | '/exclusive-moving-leads'
    | '/join'
    | '/lead-generation'
    | '/moving-company-crm'
    | '/moving-company-software'
    | '/moving-dispatch-software'
    | '/moving-estimate-software'
    | '/moving-leads'
    | '/moving-schedule-software'
    | '/open-marketplace'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/_authenticated/company'
    | '/_authenticated/customer'
    | '/_authenticated/dashboard'
    | '/blog/$slug'
    | '/cities/$city'
    | '/compare/$slug'
    | '/learn/$topic'
    | '/partners/$location'
    | '/portal/$quoteNumber'
    | '/blog/'
    | '/cities/'
    | '/partners/'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/company/analytics'
    | '/_authenticated/company/customers'
    | '/_authenticated/company/dashboard'
    | '/_authenticated/company/documents'
    | '/_authenticated/company/estimates'
    | '/_authenticated/company/exclusive'
    | '/_authenticated/company/invoices'
    | '/_authenticated/company/leads'
    | '/_authenticated/company/marketplace'
    | '/_authenticated/company/messages'
    | '/_authenticated/company/notifications'
    | '/_authenticated/company/profile'
    | '/_authenticated/company/schedule'
    | '/_authenticated/company/settings'
    | '/api/public/sla-tick'
    | '/_authenticated/admin/'
    | '/_authenticated/company/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  ExclusiveMovingLeadsRoute: typeof ExclusiveMovingLeadsRoute
  JoinRoute: typeof JoinRoute
  LeadGenerationRoute: typeof LeadGenerationRoute
  MovingCompanyCrmRoute: typeof MovingCompanyCrmRoute
  MovingCompanySoftwareRoute: typeof MovingCompanySoftwareRoute
  MovingDispatchSoftwareRoute: typeof MovingDispatchSoftwareRoute
  MovingEstimateSoftwareRoute: typeof MovingEstimateSoftwareRoute
  MovingLeadsRoute: typeof MovingLeadsRoute
  MovingScheduleSoftwareRoute: typeof MovingScheduleSoftwareRoute
  OpenMarketplaceRoute: typeof OpenMarketplaceRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CitiesCityRoute: typeof CitiesCityRoute
  CompareSlugRoute: typeof CompareSlugRoute
  LearnTopicRoute: typeof LearnTopicRoute
  PartnersLocationRoute: typeof PartnersLocationRoute
  PortalQuoteNumberRoute: typeof PortalQuoteNumberRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  ApiPublicSlaTickRoute: typeof ApiPublicSlaTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-marketplace': {
      id: '/open-marketplace'
      path: '/open-marketplace'
      fullPath: '/open-marketplace'
      preLoaderRoute: typeof OpenMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-schedule-software': {
      id: '/moving-schedule-software'
      path: '/moving-schedule-software'
      fullPath: '/moving-schedule-software'
      preLoaderRoute: typeof MovingScheduleSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-leads': {
      id: '/moving-leads'
      path: '/moving-leads'
      fullPath: '/moving-leads'
      preLoaderRoute: typeof MovingLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-estimate-software': {
      id: '/moving-estimate-software'
      path: '/moving-estimate-software'
      fullPath: '/moving-estimate-software'
      preLoaderRoute: typeof MovingEstimateSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-dispatch-software': {
      id: '/moving-dispatch-software'
      path: '/moving-dispatch-software'
      fullPath: '/moving-dispatch-software'
      preLoaderRoute: typeof MovingDispatchSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-company-software': {
      id: '/moving-company-software'
      path: '/moving-company-software'
      fullPath: '/moving-company-software'
      preLoaderRoute: typeof MovingCompanySoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moving-company-crm': {
      id: '/moving-company-crm'
      path: '/moving-company-crm'
      fullPath: '/moving-company-crm'
      preLoaderRoute: typeof MovingCompanyCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-generation': {
      id: '/lead-generation'
      path: '/lead-generation'
      fullPath: '/lead-generation'
      preLoaderRoute: typeof LeadGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusive-moving-leads': {
      id: '/exclusive-moving-leads'
      path: '/exclusive-moving-leads'
      fullPath: '/exclusive-moving-leads'
      preLoaderRoute: typeof ExclusiveMovingLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/': {
      id: '/cities/'
      path: '/cities'
      fullPath: '/cities/'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$quoteNumber': {
      id: '/portal/$quoteNumber'
      path: '/portal/$quoteNumber'
      fullPath: '/portal/$quoteNumber'
      preLoaderRoute: typeof PortalQuoteNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$location': {
      id: '/partners/$location'
      path: '/partners/$location'
      fullPath: '/partners/$location'
      preLoaderRoute: typeof PartnersLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$topic': {
      id: '/learn/$topic'
      path: '/learn/$topic'
      fullPath: '/learn/$topic'
      preLoaderRoute: typeof LearnTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$city': {
      id: '/cities/$city'
      path: '/cities/$city'
      fullPath: '/cities/$city'
      preLoaderRoute: typeof CitiesCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer': {
      id: '/_authenticated/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthenticatedCustomerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company/': {
      id: '/_authenticated/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof AuthenticatedCompanyIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sla-tick': {
      id: '/api/public/sla-tick'
      path: '/api/public/sla-tick'
      fullPath: '/api/public/sla-tick'
      preLoaderRoute: typeof ApiPublicSlaTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/company/settings': {
      id: '/_authenticated/company/settings'
      path: '/settings'
      fullPath: '/company/settings'
      preLoaderRoute: typeof AuthenticatedCompanySettingsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/schedule': {
      id: '/_authenticated/company/schedule'
      path: '/schedule'
      fullPath: '/company/schedule'
      preLoaderRoute: typeof AuthenticatedCompanyScheduleRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/profile': {
      id: '/_authenticated/company/profile'
      path: '/profile'
      fullPath: '/company/profile'
      preLoaderRoute: typeof AuthenticatedCompanyProfileRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/notifications': {
      id: '/_authenticated/company/notifications'
      path: '/notifications'
      fullPath: '/company/notifications'
      preLoaderRoute: typeof AuthenticatedCompanyNotificationsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/messages': {
      id: '/_authenticated/company/messages'
      path: '/messages'
      fullPath: '/company/messages'
      preLoaderRoute: typeof AuthenticatedCompanyMessagesRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/marketplace': {
      id: '/_authenticated/company/marketplace'
      path: '/marketplace'
      fullPath: '/company/marketplace'
      preLoaderRoute: typeof AuthenticatedCompanyMarketplaceRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/leads': {
      id: '/_authenticated/company/leads'
      path: '/leads'
      fullPath: '/company/leads'
      preLoaderRoute: typeof AuthenticatedCompanyLeadsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/invoices': {
      id: '/_authenticated/company/invoices'
      path: '/invoices'
      fullPath: '/company/invoices'
      preLoaderRoute: typeof AuthenticatedCompanyInvoicesRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/exclusive': {
      id: '/_authenticated/company/exclusive'
      path: '/exclusive'
      fullPath: '/company/exclusive'
      preLoaderRoute: typeof AuthenticatedCompanyExclusiveRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/estimates': {
      id: '/_authenticated/company/estimates'
      path: '/estimates'
      fullPath: '/company/estimates'
      preLoaderRoute: typeof AuthenticatedCompanyEstimatesRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/documents': {
      id: '/_authenticated/company/documents'
      path: '/documents'
      fullPath: '/company/documents'
      preLoaderRoute: typeof AuthenticatedCompanyDocumentsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/dashboard': {
      id: '/_authenticated/company/dashboard'
      path: '/dashboard'
      fullPath: '/company/dashboard'
      preLoaderRoute: typeof AuthenticatedCompanyDashboardRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/customers': {
      id: '/_authenticated/company/customers'
      path: '/customers'
      fullPath: '/company/customers'
      preLoaderRoute: typeof AuthenticatedCompanyCustomersRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/analytics': {
      id: '/_authenticated/company/analytics'
      path: '/analytics'
      fullPath: '/company/analytics'
      preLoaderRoute: typeof AuthenticatedCompanyAnalyticsRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCompanyRouteChildren {
  AuthenticatedCompanyAnalyticsRoute: typeof AuthenticatedCompanyAnalyticsRoute
  AuthenticatedCompanyCustomersRoute: typeof AuthenticatedCompanyCustomersRoute
  AuthenticatedCompanyDashboardRoute: typeof AuthenticatedCompanyDashboardRoute
  AuthenticatedCompanyDocumentsRoute: typeof AuthenticatedCompanyDocumentsRoute
  AuthenticatedCompanyEstimatesRoute: typeof AuthenticatedCompanyEstimatesRoute
  AuthenticatedCompanyExclusiveRoute: typeof AuthenticatedCompanyExclusiveRoute
  AuthenticatedCompanyInvoicesRoute: typeof AuthenticatedCompanyInvoicesRoute
  AuthenticatedCompanyLeadsRoute: typeof AuthenticatedCompanyLeadsRoute
  AuthenticatedCompanyMarketplaceRoute: typeof AuthenticatedCompanyMarketplaceRoute
  AuthenticatedCompanyMessagesRoute: typeof AuthenticatedCompanyMessagesRoute
  AuthenticatedCompanyNotificationsRoute: typeof AuthenticatedCompanyNotificationsRoute
  AuthenticatedCompanyProfileRoute: typeof AuthenticatedCompanyProfileRoute
  AuthenticatedCompanyScheduleRoute: typeof AuthenticatedCompanyScheduleRoute
  AuthenticatedCompanySettingsRoute: typeof AuthenticatedCompanySettingsRoute
  AuthenticatedCompanyIndexRoute: typeof AuthenticatedCompanyIndexRoute
}

const AuthenticatedCompanyRouteChildren: AuthenticatedCompanyRouteChildren = {
  AuthenticatedCompanyAnalyticsRoute: AuthenticatedCompanyAnalyticsRoute,
  AuthenticatedCompanyCustomersRoute: AuthenticatedCompanyCustomersRoute,
  AuthenticatedCompanyDashboardRoute: AuthenticatedCompanyDashboardRoute,
  AuthenticatedCompanyDocumentsRoute: AuthenticatedCompanyDocumentsRoute,
  AuthenticatedCompanyEstimatesRoute: AuthenticatedCompanyEstimatesRoute,
  AuthenticatedCompanyExclusiveRoute: AuthenticatedCompanyExclusiveRoute,
  AuthenticatedCompanyInvoicesRoute: AuthenticatedCompanyInvoicesRoute,
  AuthenticatedCompanyLeadsRoute: AuthenticatedCompanyLeadsRoute,
  AuthenticatedCompanyMarketplaceRoute: AuthenticatedCompanyMarketplaceRoute,
  AuthenticatedCompanyMessagesRoute: AuthenticatedCompanyMessagesRoute,
  AuthenticatedCompanyNotificationsRoute:
    AuthenticatedCompanyNotificationsRoute,
  AuthenticatedCompanyProfileRoute: AuthenticatedCompanyProfileRoute,
  AuthenticatedCompanyScheduleRoute: AuthenticatedCompanyScheduleRoute,
  AuthenticatedCompanySettingsRoute: AuthenticatedCompanySettingsRoute,
  AuthenticatedCompanyIndexRoute: AuthenticatedCompanyIndexRoute,
}

const AuthenticatedCompanyRouteWithChildren =
  AuthenticatedCompanyRoute._addFileChildren(AuthenticatedCompanyRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRouteWithChildren
  AuthenticatedCustomerRoute: typeof AuthenticatedCustomerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompanyRoute: AuthenticatedCompanyRouteWithChildren,
  AuthenticatedCustomerRoute: AuthenticatedCustomerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  ExclusiveMovingLeadsRoute: ExclusiveMovingLeadsRoute,
  JoinRoute: JoinRoute,
  LeadGenerationRoute: LeadGenerationRoute,
  MovingCompanyCrmRoute: MovingCompanyCrmRoute,
  MovingCompanySoftwareRoute: MovingCompanySoftwareRoute,
  MovingDispatchSoftwareRoute: MovingDispatchSoftwareRoute,
  MovingEstimateSoftwareRoute: MovingEstimateSoftwareRoute,
  MovingLeadsRoute: MovingLeadsRoute,
  MovingScheduleSoftwareRoute: MovingScheduleSoftwareRoute,
  OpenMarketplaceRoute: OpenMarketplaceRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  BlogSlugRoute: BlogSlugRoute,
  CitiesCityRoute: CitiesCityRoute,
  CompareSlugRoute: CompareSlugRoute,
  LearnTopicRoute: LearnTopicRoute,
  PartnersLocationRoute: PartnersLocationRoute,
  PortalQuoteNumberRoute: PortalQuoteNumberRoute,
  BlogIndexRoute: BlogIndexRoute,
  CitiesIndexRoute: CitiesIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  ApiPublicSlaTickRoute: ApiPublicSlaTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
