
ALTER TABLE public.quotes
  ADD COLUMN IF NOT EXISTS origin_address text,
  ADD COLUMN IF NOT EXISTS destination_address text,
  ADD COLUMN IF NOT EXISTS origin_state text,
  ADD COLUMN IF NOT EXISTS destination_state text,
  ADD COLUMN IF NOT EXISTS distance_miles numeric(10,2),
  ADD COLUMN IF NOT EXISTS move_type text,
  ADD COLUMN IF NOT EXISTS move_size text,
  ADD COLUMN IF NOT EXISTS estimated_cubic_feet numeric(10,2),
  ADD COLUMN IF NOT EXISTS estimated_weight_lbs numeric(10,2),
  ADD COLUMN IF NOT EXISTS truck_size text,
  ADD COLUMN IF NOT EXISTS num_movers integer,
  ADD COLUMN IF NOT EXISTS labor_hours numeric(6,2),
  ADD COLUMN IF NOT EXISTS unpacking boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS junk_removal boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS piano boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS safe boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS gym_equipment boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS appliances boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS fragile_items boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS insurance_tier text,
  ADD COLUMN IF NOT EXISTS origin_stairs integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS destination_stairs integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS origin_elevator boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS destination_elevator boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS origin_long_carry boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS destination_long_carry boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS preferred_time text,
  ADD COLUMN IF NOT EXISTS flexible_date boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS inventory jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS breakdown jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS details jsonb NOT NULL DEFAULT '{}'::jsonb;
